INSERT INTO `study_version` (`version_id`, `activity_version`, `custom_study_id`, `study_version`, `consent_version`) VALUES (1, 1, 'OpenStudy002', 1, 1);

INSERT INTO `notification` (`notification_id`, `notification_type`, `study_id`, `custom_study_id`, `notification_subType`, `is_anchor_date`, `created_by`, `created_on`, `schedule_date`, `schedule_time`, `notification_action`, `notification_done`, `notification_schedule_type`, `notification_sent`, `notification_status`, `notification_text`, `questionnarie_id`, `app_id`) VALUES (12, 'ST', 1433, 'studytestxyz', 'studyEvent', 0, 82, '2020-09-03 09:47:28', '2020-09-03', '09:47:28', 0, 1, 'immediate', 0, 0, 'The study studytest has been resumed..', 1, 'GCPMS001');

INSERT INTO `studies` (`id`, `custom_study_id`, `name`, `full_name`, `type`, `platform`, `category`, `research_sponsor`, `data_partner`, `tentative_duration`, `tentative_duration_weekmonth`, `description`, `enrolling_participants`, `retain_participant`, `allow_rejoin`, `inbox_email_address`, `created_by`, `created_on`, `modified_by`, `modified_on`, `status`, `thumbnail_image`, `media_link`, `allow_rejoin_text`, `study_website`, `study_tagline`, `study_pre_active_flag`, `has_activity_draft`, `has_consent_draft`, `has_study_draft`, `is_live`, `version`, `has_activitetask_draft`, `has_questionnaire_draft`, `enrollmentdate_as_anchordate`, `app_id`, `org_id`) VALUES (1, 'OpenStudy002', 'XSSTEST', 'XSSTEST', 'GT', 'I,A', '8', 'cdc', '11', 3, 'Months', 'xscszc', 'Yes', 'Yes', 'Yes', 'test@grr.la', 59, '2020-05-15 05:30:09', 59, '2020-05-15 11:30:14', 'Pre-launch', 'STUDY_XX_05152020055149.jpg', '', 'XSSTEST', '', 'XSSTEST', 'N', 0, 1, 1, 0, 0, 1, 1, 'Y', 'APP', 'OrgName');

INSERT INTO `questions` (`id`, `active`, `add_line_chart`, `created_by`, `created_on`, `description`, `modified_by`, `modified_on`, `question`, `response_type`, `status`, `use_anchor_date`, `use_stastic_data`, `allow_healthkit`, `anchor_date_id`) VALUES (1, 1, 'No', 104, '2020-08-12 11:28:14', 0, 104, '2020-08-17 16:19:00', 'Please specify the date of appearance of acne on your skin', 10, 1, 1, 'No', 'No', 225);

INSERT INTO `questionnaires_steps` (`step_id`, `questionnaires_id`, `instruction_form_id`, `step_short_title`, `step_type`, `sequence_no`, `destination_step`, `repeatable`, `skiappable`, `active`, `status`) VALUES (1, 1, 1, '1time', 'Question', 1, 60873, 'No', 'Yes', '1', 1);

INSERT INTO `questionnaires` (`id`, `study_id`, `frequency`, `title`, `study_lifetime_start`, `study_lifetime_end`, `short_title`, `repeat_questionnaire`, `created_by`, `created_date`, `modified_by`, `modified_date`, `active`, `status`, `custom_study_id`, `is_live`, `version`, `is_Change`, `schedule_type`) VALUES (2, 2, 'Daily', 'Test Notification Chart 001', '2020-08-28', '2022-04-19', 'testchart01', 600, 0, '2020-08-28 08:42:33', 0, '2020-08-28 08:46:00', 1, 1, 'covid3', 1, 1, 1, 'Regular');

INSERT INTO `study_sequence` (`study_sequence_id`, `study_id`, `actions`, `basic_info`, `check_list`, `comprehension_test`, `consent_edu_info`, `e_consent`, `eligibility`, `miscellaneous_branding`, `miscellaneous_notification`, `miscellaneous_resources`, `over_view`, `setting_admins`, `study_dashboard_chart`, `study_dashboard_stats`, `study_exc_active_task`, `study_exc_questionnaries`) VALUES (10633, 678574, 'N', 'Y', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N');

